"""
maya_exporter.py
----------------
Generate a Maya ASCII (.ma) scene from RC camera data.

Each camera gets:
  - A transform node  (position + rotation from XMP)
  - A camera shape    (focal length from XMP, 35mm film gate)
  - An imagePlane     (linked to the corresponding undistorted PNG)

Coordinate conversion
---------------------
  RC position  (metres)   → Maya translate (centimetres, ×100)
  RC rotation  R_w2c      → Maya rotate: Euler XYZ from R_c2w = R_w2c.T
  Film gate               → 36 mm × 24 mm  (1.41732 × 0.94488 inches)

Camera naming
-------------
  Stem is sanitised (non-alphanumeric → '_').
  If the sanitised stem is longer than 24 characters, the last 14 chars are used.
  Final name is prefixed with 'cam_'.
"""

from __future__ import annotations

import re
from datetime import datetime
from pathlib import Path
from typing import Optional

from .xmp_parser import CameraData

# Maya film aperture for 35mm full frame (in inches)
_FILM_H_INCH = 36.0 / 25.4   # 1.41732...
_FILM_V_INCH = 24.0 / 25.4   # 0.94488...

_MAX_STEM = 24
_SHORT_STEM = 14


def _sanitise_name(stem: str) -> str:
    """Convert a filename stem to a valid Maya node name prefix."""
    sanitised = re.sub(r"[^A-Za-z0-9]", "_", stem)
    # Trim to last _SHORT_STEM chars if too long
    if len(sanitised) > _MAX_STEM:
        sanitised = sanitised[-_SHORT_STEM:]
    # Maya names cannot start with a digit
    if sanitised and sanitised[0].isdigit():
        sanitised = "n" + sanitised
    return sanitised


def _camera_block(cam: CameraData, png_path: Optional[Path], index: int) -> str:
    """Return the Maya ASCII text for one camera + image plane."""
    safe = _sanitise_name(cam.source_stem)
    grp_name = f"cam_{safe}_grp"
    cam_name = f"cam_{safe}"
    shape_name = f"cam_{safe}Shape"
    ip_name = f"cam_{safe}_imgPlane"

    tx, ty, tz = cam.position_cm
    rx, ry, rz = cam.euler_xyz_deg
    fl = cam.focal_length_35mm

    lines: list[str] = []

    # ── Transform node ────────────────────────────────────────────────────
    lines.append(f'createNode transform -n "{grp_name}";')
    lines.append(f'    setAttr ".t" -type "double3" {tx:.6f} {ty:.6f} {tz:.6f};')
    lines.append(f'    setAttr ".r" -type "double3" {rx:.6f} {ry:.6f} {rz:.6f};')
    lines.append("")

    # ── Camera shape ──────────────────────────────────────────────────────
    lines.append(f'createNode camera -n "{shape_name}" -p "{grp_name}";')
    lines.append(f'    rename -uid "CAM_{index:04d}";')
    lines.append(f'    setAttr ".fl" {fl:.6f};')
    lines.append(f'    setAttr ".cap" -type "double2" {_FILM_H_INCH:.6f} {_FILM_V_INCH:.6f};')
    lines.append("")

    # ── Image plane (only when a PNG was produced) ────────────────────────
    if png_path is not None:
        png_str = str(png_path).replace("\\", "/")
        lines.append(f'createNode imagePlane -n "{ip_name}" -p "{shape_name}";')
        lines.append(f'    setAttr ".fn" -type "string" "{png_str}";')
        lines.append(f'    setAttr ".fc" 1;')          # frame offset
        lines.append(f'    setAttr ".d" 100;')          # depth
        lines.append(f'    setAttr ".fit" 4;')          # fit = to size
        lines.append("")
        lines.append(f'connectAttr "{ip_name}.message" "{shape_name}.imagePlane" -na;')
        lines.append("")

    return "\n".join(lines)


def write_maya_scene(
    cameras: list[CameraData],
    png_paths: dict[str, Optional[Path]],
    output_path: str | Path,
    scene_unit: str = "centimeter",
) -> Path:
    """
    Write a Maya ASCII file containing all cameras and image planes.

    Parameters
    ----------
    cameras:
        List of CameraData parsed from XMP files.
    png_paths:
        Mapping from source stem to the corresponding undistorted PNG path
        (or None if no PNG was produced for that stem).
    output_path:
        Destination .ma file path.
    scene_unit:
        Maya linear unit (default "centimeter").

    Returns
    -------
    Path to the written file.
    """
    output_path = Path(output_path)
    output_path.parent.mkdir(parents=True, exist_ok=True)

    now = datetime.now().strftime("%Y/%m/%d %H:%M:%S")
    header = f"""\
//Maya ASCII 2024 scene
//Name: {output_path.name}
//Generated by RC Helper on {now}
//Codeset: UTF-8
requires maya "2024";
currentUnit -l {scene_unit} -a degree -t film;
fileInfo "application" "RC Helper";
fileInfo "product" "RC Helper 0.1.0";

"""

    body_parts: list[str] = []
    for idx, cam in enumerate(cameras):
        png = png_paths.get(cam.source_stem)
        body_parts.append(_camera_block(cam, png, idx))

    content = header + "\n".join(body_parts)

    output_path.write_text(content, encoding="utf-8")
    return output_path
